name: API Tests In Parallel

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

jobs:
  Chrome_Ubuntu_All_Tests:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.0

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.4

      - name: Run tests
        continue-on-error: true
        run: >
          mvn clean test -Dtest="testCases.APITests.**"
          -DparallelMode="CLASSES"
          -DthreadCount="6"

      - name: Generate Allure report
        run: mvn allure:report

      - name: Copy patch file to allure-maven-plugin folder
        run: cp src/main/resources/allow-file-access_open-report_chrome_windows.bat target/site/allure-maven-plugin

      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: Allure Report API Tests In Parallel Chrome Ubuntu
          path: "target/site/allure-maven-plugin"
